### generate small array by repeating a small array

In [6]:
import numpy as np

In [10]:
sarray = np.array([[2,4],[5,6]])
sarray

repeat = np.tile(sarray,(2,2))
print(repeat)

[[2 4 2 4]
 [5 6 5 6]
 [2 4 2 4]
 [5 6 5 6]]


### array generated using element indexes so that elements appear in ascending order

In [8]:
shape= (4,4)
#defines shape of array

array = np.arange(np.prod(shape)).reshape(shape)
#np.prod()=gives total number of elements
# here 4x4=16,therefore we have 16elements
# np.arange(np.prod())=generates array elements from 0 to np.prod(shape)-1
# np.reshape()= convert the generated array to 4x4

print("array with elements indexes in ascending order:\n",array)

array with elements indexes in ascending order:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [9]:
shape=(5,5)
totalelements=np.prod(shape)#5x5=25
lineararray=np.arange(totalelements)#array9[0,1,2,3,4.....,24]
reshapedarray = lineararray.reshape(shape)
print(reshapedarray)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
